{% set version = "1.35.3" %}

package:
  name: nanoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nanoplot/NanoPlot-{{ version }}.tar.gz
  sha256: 3bae306f270edb05ec0b8ea155382c803aa3af9dcf8fa2668e79f38618383541

build:
  entry_points:
    - NanoPlot=nanoplot.NanoPlot:main
  number: 0
  noarch: python

requirements:
  host:
    - python >=3
    - setuptools
  run:
    - python >=3
    - biopython
    - pysam >0.10.0.0
    - pandas >=0.22.0
    - numpy
    - scipy
    - python-dateutil
    - nanoget >=1.14.0
    - nanomath >=1.0.0
    - plotly >=4.9.0
    - pyarrow
    - python-kaleido

test:
  imports:
    - nanoplot
  commands:
    - NanoPlot --help

about:
  home: https://github.com/wdecoster/NanoPlot
  license: GPL-3.0-only
  summary: 'Plotting suite for long read sequencing data and alignments'
  license_family: GPL
