{% set name = "odamnet" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #  url: https://github.com/MOohTus/ODAMNet/archive/refs/tags/v1.1.1.tar.gz
  #  sha256: e1c8fc4c8ffbfc47a796ec70e155c3ec600563eb64d2525851ab72e54f6528ec
  url: https://github.com/MOohTus/ODAMNet/releases/download/v1.1.1/ODAMNet-1.1.1.tar.gz
  sha256: 2f31167f34b0d4d105179b6d9aa9d7d0183a91c9280bd7622e2379c2b534f860

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - alive-progress >=2.4.1
    - click >=8.0.1
    - click-option-group >=0.5.3
    - multixrank >=0.1
    - ndex2 >=3.5.0
    - networkx ==2.5
    - pandas >=1.3.5
    - python >=3.9
    - requests >=2.27.1
    - scipy >=1.7.3
    - sparqlwrapper >=1.8.5
      #- sphinx-tabs ==3.4.0
      #- docutils ==0.18.0
    - statsmodels >=0.13.2

test:
  imports:
    - odamnet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ODAMNet/1.1.0/
  summary: Study molecular relationships between chemicals and rare diseases
  dev_url: https://github.com/MOohTus/ODAMNet/tree/v1.1.1
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Morgane Terezol
